### ISSUE TITLE
Solution doesn't compile

### ISSUE THREAD

**Issue by abukres** [XCESS-NL/MSBuild-for-DNN#22]
The Solution doesn't compile:
The solution doesn't compile
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "BuildDnnManifest" task failed unexpectedly.
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Dnn.MsBuild.Tasks.Parsers.UserControlParser.<Parse>b__8_0(String fileName) in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\Parsers\UserControlParser.cs:line 74
   at Dnn.MsBuild.Tasks.Extensions.LinqExtensionMethods.ForEach[TElement](IEnumerable`1 source, Action`1 act) in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\Extensions\LinqExtensionMethods.cs:line 39
   at Dnn.MsBuild.Tasks.Parsers.UserControlParser.Parse(IEnumerable`1 sourceFiles) in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\Parsers\UserControlParser.cs:line 54
   at Dnn.MsBuild.Tasks.BuildDnnManifest.GetUserControls(String basePath, IEnumerable`1 resourceFiles) in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\BuildDnnManifest.cs:line 156
   at Dnn.MsBuild.Tasks.BuildDnnManifest.CreateProjectPackageData() in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\BuildDnnManifest.cs:line 95
   at Dnn.MsBuild.Tasks.BuildDnnManifest.CreateTaskData() in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\BuildDnnManifest.cs:line 108
   at Dnn.MsBuild.Tasks.BuildDnnManifest.Execute() in C:\inetpub\wwwroot\MSBuild-for-DNN\Dnn.MsBuild.Tasks\BuildDnnManifest.cs:line 58
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	XCESS.DNN.Module

**Comment by serge-van-der-ven** [comment]
Added a check in the UserControlParser. If the DesktopModule folder name does not exist in the UserControls filename, the file is simply ignored.
Notice that this project was never completed and is no longer maintained - We are currently working on a new revised solution base on .NET core.
